### ISSUE TITLE
.pyc files in tarball from pypi

### ISSUE THREAD

**Issue by fscherf** [borgstrom/django-simple-menu#45]
All tarballs from pypi i tested are containing 
- /menu/templatetags/__init__.pyc
- /menu/templatetags/menu.pyc

**Comment by rschwebel** [comment]
Hi,
This seems to be more than a cosmetic issue. I have a package that depends on django-simple-menu, and if I try to install it in development mode (python setup.py develop), it crashes while installing django-simple-menu (see exception below).
With a local checkout of django-simple-menu, then running 'python setup.py sdist' and using the resulting tarball instead of the one from pypi containing the .pyc files, everything works nicely.
Please use the 'python setup.py sdist' and 'python setup.py upload' mechanism to generate and upload the archives.

rsc





[issue.txt](https://github.com/borgstrom/django-simple-menu/files/230040/issue.txt)

**Comment by borgstrom** [comment]
Thanks for the report (and pardon the lag).

Version 1.2.1 has just been published to pypi and I've confirmed there's no `.pyc` files in the tarball.
